package com.compomics.relims.gui;

import com.compomics.mslims.db.accessors.Project;
import com.compomics.relims.concurrent.ProjectRunner;
import com.compomics.relims.conf.RelimsProperties;
import com.compomics.relims.model.mslims.MsLimsProvider;
import com.google.common.io.Files;
import org.apache.log4j.Logger;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * This class is a
 */
public class RelimsGUI implements Observer {

    static private ExecutorService iService = Executors.newSingleThreadExecutor();

    private static Logger logger = Logger.getLogger(RelimsGUI.class);

    private JPanel jpanContent;
    private JButton btnStart;
    private JScrollPane scrollLayout;
    private JTextArea txtMessagePanel;
    private JButton iStopButton;
    private JPanel jpanButtons;

    private int iProjectCounter = 0;
    public ResultObserver iResultObserver;

    public static void main(String[] args) {
        JFrame lFrame = new JFrame("RelimsGUI");
        lFrame.setContentPane(new RelimsGUI().jpanContent);
        lFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        lFrame.pack();
        lFrame.setVisible(true);

    }

    /**
     * Construct the GUI
     */
    public RelimsGUI() {
        $$$setupUI$$$();
        txtMessagePanel.setEditable(false);
        TextAreaAppender.setTextArea(txtMessagePanel);
        logger.debug("initialized GUI");
        logger.debug("setting listeners");


        setListeners();

        /**
         * Sets an UncaughtExceptionHandler and executes the thread by the ExecutorsService
         */
        Thread.setDefaultUncaughtExceptionHandler(new MyUncaughtExceptionHandler());

    }

    /**
     * Append the button listeners of the GUI
     */
    private void setListeners() {
        btnStart.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent aActionEvent) {

                iProjectCounter = 0;
                logger.debug("clicked start button");
                int lRandomSize = RelimsProperties.getRandomProjectAttempts();
                logger.debug("selecting " + lRandomSize + " random projects");
                ArrayList<Project> lRandomProjects = MsLimsProvider.getInstance().getRandomProjects(lRandomSize);

//                lRandomProjects.addAll(0, MsLimsProvider.getInstance().getProjects(new int[]{731}));

                try {
                    iResultObserver = new ResultObserver();
                } catch (IOException e) {
                    logger.error(e.getMessage(), e);
                }

                for (Project lProject : lRandomProjects) {
                    ProjectRunner lProjectRunner = new ProjectRunner(lProject);
                    lProjectRunner.addObserver(RelimsGUI.this);
                    lProjectRunner.addObserver(iResultObserver);
                    iService.execute(lProjectRunner);
                }
            }
        });


        iStopButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent aActionEvent) {
                shutdown();
            }
        });
    }

    private void shutdown() {
        List<Runnable> lRunnables = iService.shutdownNow();
        for (Runnable lRunnable : lRunnables) {
            logger.debug("shutting down " + lRunnable.toString());
        }
        iService = Executors.newSingleThreadExecutor();
    }


    public void update(Observable aObservable, Object o) {
        synchronized (this) {
            iProjectCounter++;
            logger.debug("PROJECT SUCCES COUNT " + iProjectCounter + "(" + o.toString() + ").");
            if (iProjectCounter == RelimsProperties.getMaxSucces()) {
                shutdown();
            }
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jpanContent = new JPanel();
        jpanContent.setLayout(new GridBagLayout());
        jpanContent.setEnabled(true);
        jpanContent.setPreferredSize(new Dimension(1000, 600));
        scrollLayout = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        jpanContent.add(scrollLayout, gbc);
        txtMessagePanel = new JTextArea();
        txtMessagePanel.setEditable(false);
        txtMessagePanel.setSelectionEnd(0);
        txtMessagePanel.setSelectionStart(0);
        txtMessagePanel.setText("");
        scrollLayout.setViewportView(txtMessagePanel);
        jpanButtons = new JPanel();
        jpanButtons.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        jpanContent.add(jpanButtons, gbc);
        btnStart = new JButton();
        btnStart.setText("Start");
        jpanButtons.add(btnStart);
        iStopButton = new JButton();
        iStopButton.setText("Stop");
        jpanButtons.add(iStopButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jpanContent;
    }

    private class ResultObserver implements Observer {

        public BufferedWriter iObservingWriter;

        private ResultObserver() throws IOException {
            File lFile = RelimsProperties.getTmpFile("runner.results.csv");
            iObservingWriter = Files.newWriter(lFile, Charset.defaultCharset());
        }

        public void update(Observable aObservable, Object o) {
            try {
                iObservingWriter.write(o.toString());
                iObservingWriter.newLine();
                iObservingWriter.flush();
            } catch (IOException e) {
                logger.error(e.getMessage(), e);
            }
        }

        public void close() throws IOException {
            if (iObservingWriter != null) {
                iObservingWriter.flush();
                iObservingWriter.close();
            }
        }
    }
}
